### ISSUE TITLE
RHEL9 DotNet containers tested on OpenShift 4

### ISSUE THREAD

**Issue by phracek** [sclorg/ansible-tests#40]
It would be nice to test DotNet containers on OpenShift 4 as we do it for RHEL8.

WDYT? Does it make sense?
@aslicerh Do you have time to handle it and drive it?

**Comment by aslicerh** [comment]
Do you mean RHEL9/UBI9 based .NET containers? If so, we don't ship any of those, so there is nothing to test.

Or do you mean testing the RHEL8/UBI8 based .NET containers on a RHEL9 Openshift host? If so, I would be willing to look into that.

**Comment by phracek** [comment]
@aslicerh Yeah, I have meant RHEL9/UBI9 based .NET container. Closing this issue.
